create table orcamentos {

    id bigint not null auto_increment,
    nome varchar(100),
    razaoSocial varchar(100),
    nomeFantasia varchar(100),
    email varchar(100),
    cidade varchar(100) not null,
    uf char(2) not null,
    data date,
    alturaDaParede double,
    larguraDaParede double,
    alturaDosModulos double,
    larguraDosModulos double,
    areaDosModulos double,
    totalDeModulosInteiros INT,
    totalDeModulosCantoneira INT,
    totalDeModulosNicho INT,
    totalDeModulosDuplos INT,
    totalDeTopos INT,
    totalDeToposNicho INT,
    totalDeToposDuplos INT,
    totalDePlacasHorizontais INT,
    totalDePlacasVerticais INT,
    totalDeVasos INT,
    totalDeBolsasDeSubstrato INT,
    totalDeIniciaisFinais INT,
    totalDePinosDeTravamento INT,
    totalDePlacasNicho INT,
    totalDePlacasDuplo INT,
    totalDePlantas INT,
    totalGotejadores INT,
    totalTuboCego DOUBLE,
    totalCotovelos INT,
    totalTes INT,
    totalFinalDeLinha INT,
    totalConectorInicial INT,
    totalParafusos INT,
    totalBuchas INT,
    totalDePlacasCantoneiras INT,
    totalDePlacasVerticaisCantoneira INT,
    totalDeUniaoCantoneira INT,
    totalDeVasosCantoneira INT,
    totalDeBolsaDeSubstratoCantoneira INT,
    precoTotal decimal(10,2),
    precoTotalEstrutura decimal(10,2),
    precoTotalIrrigacao decimal(10,2),
    precoTotalFixacao decimal(10,2),

    primary key(id)

}